/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VehicleOwnership } from './VehicleOwnership.js';
export * as factories from './factories/index.js';
export { VehicleOwnership__factory } from './factories/VehicleOwnership__factory.js';