/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace VehicleOwnership {
      
    export type OwnershipRecordStruct = {owner: AddressLike, timestamp: BigNumberish}

    export type OwnershipRecordStructOutput = [owner: string, timestamp: bigint] & {owner: string, timestamp: bigint }
  
    }

  export interface VehicleOwnershipInterface extends Interface {
    getFunction(nameOrSignature: "getCurrentOwner" | "getOwnershipHistory" | "getTotalVehicles" | "getVehicleById" | "getVehicleByNumber" | "isVehicleNumberRegistered" | "registerVehicle" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OwnershipTransferred" | "VehicleRegistered"): EventFragment;

    encodeFunctionData(functionFragment: 'getCurrentOwner', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getOwnershipHistory', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getTotalVehicles', values?: undefined): string;
encodeFunctionData(functionFragment: 'getVehicleById', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getVehicleByNumber', values: [string]): string;
encodeFunctionData(functionFragment: 'isVehicleNumberRegistered', values: [string]): string;
encodeFunctionData(functionFragment: 'registerVehicle', values: [string, string]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [BigNumberish, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'getCurrentOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOwnershipHistory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTotalVehicles', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getVehicleById', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getVehicleByNumber', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isVehicleNumberRegistered', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerVehicle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace OwnershipTransferredEvent {
      export type InputTuple = [vehicleId: BigNumberish, fromOwner: AddressLike, toOwner: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [vehicleId: bigint, fromOwner: string, toOwner: string, timestamp: bigint];
      export interface OutputObject {vehicleId: bigint, fromOwner: string, toOwner: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VehicleRegisteredEvent {
      export type InputTuple = [vehicleId: BigNumberish, vehicleNumber: string, vehicleModel: string, owner: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [vehicleId: bigint, vehicleNumber: string, vehicleModel: string, owner: string, timestamp: bigint];
      export interface OutputObject {vehicleId: bigint, vehicleNumber: string, vehicleModel: string, owner: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface VehicleOwnership extends BaseContract {
    
    connect(runner?: ContractRunner | null): VehicleOwnership;
    waitForDeployment(): Promise<this>;

    interface: VehicleOwnershipInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getCurrentOwner: TypedContractMethod<
      [vehicleId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getOwnershipHistory: TypedContractMethod<
      [vehicleId: BigNumberish, ],
      [VehicleOwnership.OwnershipRecordStructOutput[]],
      'view'
    >
    

    
    getTotalVehicles: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getVehicleById: TypedContractMethod<
      [vehicleId: BigNumberish, ],
      [[bigint, string, string, string, bigint] & {id: bigint, vehicleNumber: string, vehicleModel: string, currentOwner: string, registeredAt: bigint }],
      'view'
    >
    

    
    getVehicleByNumber: TypedContractMethod<
      [vehicleNumber: string, ],
      [[bigint, string, string, string, bigint] & {id: bigint, vNumber: string, vehicleModel: string, currentOwner: string, registeredAt: bigint }],
      'view'
    >
    

    
    isVehicleNumberRegistered: TypedContractMethod<
      [vehicleNumber: string, ],
      [boolean],
      'view'
    >
    

    
    registerVehicle: TypedContractMethod<
      [vehicleNumber: string, vehicleModel: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [vehicleId: BigNumberish, newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getCurrentOwner'): TypedContractMethod<
      [vehicleId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getOwnershipHistory'): TypedContractMethod<
      [vehicleId: BigNumberish, ],
      [VehicleOwnership.OwnershipRecordStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getTotalVehicles'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getVehicleById'): TypedContractMethod<
      [vehicleId: BigNumberish, ],
      [[bigint, string, string, string, bigint] & {id: bigint, vehicleNumber: string, vehicleModel: string, currentOwner: string, registeredAt: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getVehicleByNumber'): TypedContractMethod<
      [vehicleNumber: string, ],
      [[bigint, string, string, string, bigint] & {id: bigint, vNumber: string, vehicleModel: string, currentOwner: string, registeredAt: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'isVehicleNumberRegistered'): TypedContractMethod<
      [vehicleNumber: string, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'registerVehicle'): TypedContractMethod<
      [vehicleNumber: string, vehicleModel: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [vehicleId: BigNumberish, newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'VehicleRegistered'): TypedContractEvent<VehicleRegisteredEvent.InputTuple, VehicleRegisteredEvent.OutputTuple, VehicleRegisteredEvent.OutputObject>;

    filters: {
      
      'OwnershipTransferred(uint256,address,address,uint256)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'VehicleRegistered(uint256,string,string,address,uint256)': TypedContractEvent<VehicleRegisteredEvent.InputTuple, VehicleRegisteredEvent.OutputTuple, VehicleRegisteredEvent.OutputObject>;
      VehicleRegistered: TypedContractEvent<VehicleRegisteredEvent.InputTuple, VehicleRegisteredEvent.OutputTuple, VehicleRegisteredEvent.OutputObject>;
    
    };
  }