const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  console.log("==================================================");
  console.log("Starting Vehicle Ownership Contract Deployment...");
  console.log("==================================================");

  const [deployer] = await hre.ethers.getSigners();
  const network = await hre.ethers.provider.getNetwork();

  console.log(`Deployer Address: ${deployer.address}`);
  console.log(`Deployer Balance: ${hre.ethers.formatEther(await hre.ethers.provider.getBalance(deployer.address))} ETH`);
  console.log(`Network Name:     ${network.name === "unknown" ? "localhost" : network.name} (Chain ID: ${network.chainId})`);

  // Deploy VehicleOwnership contract
  const VehicleOwnership = await hre.ethers.getContractFactory("VehicleOwnership");
  console.log("Deploying VehicleOwnership contract...");
  const vehicleOwnership = await VehicleOwnership.deploy();

  await vehicleOwnership.waitForDeployment();

  const contractAddress = await vehicleOwnership.getAddress();
  console.log(`SUCCESS: VehicleOwnership deployed to: ${contractAddress}`);

  // Obtain contract artifact for ABI
  const artifact = await hre.artifacts.readArtifact("VehicleOwnership");

  // Prepare config content for frontend
  const configDir = path.join(__dirname, "../src/config");
  if (!fs.existsSync(configDir)) {
    fs.mkdirSync(configDir, { recursive: true });
  }

  const configPath = path.join(configDir, "contractConfig.js");
  const configContent = `/**
 * Auto-generated Contract Configuration for Phase 4 Frontend Integration.
 * DO NOT EDIT MANUALLY - Generated by scripts/deploy.cjs
 */

export const CONTRACT_ADDRESS = "${contractAddress}";

export const NETWORK_INFO = {
  name: "${network.name === "unknown" ? "localhost" : network.name}",
  chainId: ${network.chainId.toString()},
  rpcUrl: "http://127.0.0.1:8545",
};

export const CONTRACT_ABI = ${JSON.stringify(artifact.abi, null, 2)};

export default {
  address: CONTRACT_ADDRESS,
  abi: CONTRACT_ABI,
  network: NETWORK_INFO,
};
`;

  fs.writeFileSync(configPath, configContent);
  console.log(`Configuration saved to: ${configPath}`);
  console.log("==================================================");
  console.log("Deployment completed successfully.");
}

main().catch((error) => {
  console.error("Deployment failed:", error);
  process.exitCode = 1;
});
